// <auto-generated />
using System;
using InsuraceProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Claims.Migrations
{
    [DbContext(typeof(AuditContext))]
    [Migration("20230608101502_AddDamageCost")]
    partial class AddDamageCost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuraceProject.API.DbEntities.ClaimAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DamageCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HttpRequestType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ClaimAudits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimId = "1",
                            Created = new DateTime(2023, 6, 8, 10, 15, 2, 48, DateTimeKind.Utc).AddTicks(5018),
                            DamageCost = 122.22m,
                            HttpRequestType = "Https"
                        },
                        new
                        {
                            Id = 2,
                            ClaimId = "2",
                            Created = new DateTime(2023, 5, 27, 10, 15, 2, 48, DateTimeKind.Utc).AddTicks(5026),
                            DamageCost = 5.2m,
                            HttpRequestType = "Https"
                        },
                        new
                        {
                            Id = 3,
                            ClaimId = "3",
                            Created = new DateTime(2023, 6, 6, 10, 15, 2, 48, DateTimeKind.Utc).AddTicks(5034),
                            DamageCost = 34.13m,
                            HttpRequestType = "Https"
                        },
                        new
                        {
                            Id = 4,
                            ClaimId = "4",
                            Created = new DateTime(2023, 6, 3, 10, 15, 2, 48, DateTimeKind.Utc).AddTicks(5035),
                            DamageCost = 0m,
                            HttpRequestType = "Https"
                        });
                });

            modelBuilder.Entity("InsuraceProject.API.DbEntities.CoverAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("HttpRequestType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("CoverAudits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverId = "1",
                            Created = new DateTime(2023, 6, 8, 10, 15, 2, 48, DateTimeKind.Utc).AddTicks(5201),
                            HttpRequestType = "Https"
                        },
                        new
                        {
                            Id = 2,
                            CoverId = "2",
                            Created = new DateTime(2023, 6, 5, 10, 15, 2, 48, DateTimeKind.Utc).AddTicks(5204),
                            HttpRequestType = "Https"
                        },
                        new
                        {
                            Id = 3,
                            CoverId = "3",
                            Created = new DateTime(2023, 5, 29, 10, 15, 2, 48, DateTimeKind.Utc).AddTicks(5206),
                            HttpRequestType = "Https"
                        },
                        new
                        {
                            Id = 4,
                            CoverId = "4",
                            Created = new DateTime(2023, 6, 3, 10, 15, 2, 48, DateTimeKind.Utc).AddTicks(5207),
                            HttpRequestType = "Https"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
